import type { Metadata } from "next";
import "./globals.css";
import Home from "@/components/Home";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className=" relative overflow-hidden">
          {children}
          <Home />
        </main>
      </body>
    </html>
  );
}
